## About Dataset

**Content:**

This data set contains details of a bank's customers and the target variable is a binary variable reflecting the fact whether the customer left the bank (closed his account) or he continues to be a customer.

**Acknowledgements:**

Big thanks to https://www.superdatascience.com/pages/deep-learning

Banner Photo by Sharon McCutcheon on Unsplas

# Artificial Neural Network

In [ ]:
# Mount to the colab
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# 1. Libraries

In [ ]:
# Import the libraries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import tensorflow  as tf
import sklearn

In [ ]:
tf.__version__

'2.15.0'

# 2. import Dataset

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/ANN/Churn_Modelling.csv")
# All the columns except last one
x = df.iloc[:, 3:-1].values
# Except all the columns only last column needed
y = df.iloc[:, -1].values

In [ ]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]

In [ ]:
print(y)

[1 0 1 ... 1 1 0]

# 3. Data Pre-processing

1. Encoding Categorical data

Label encoding "Gender" column

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])

In [ ]:
x

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

OneHotEnoding for "Geography" column

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

2. Spliting the dataset for train and test

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, train_size=0.7, random_state=0)

3. Feature scaling

In [ ]:
# Feature Scaling for neural network
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

# 4. Building ANN

In [ ]:
# Initialize the ANN
ann = tf.keras.models.Sequential()

# Adding input layer and first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Adding second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Adding the output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# 5. Training ANN

1. Compiling the ANN

In [ ]:
ann.compile(optimizer = 'adam',
            loss = 'binary_crossentropy',
            metrics = ['accuracy'])

Training the ANN on training set

In [ ]:
# training the data
history = ann.fit(
    x_train,y_train,
    batch_size=32,
    epochs=100,
    verbose=True
)

Epoch 1/100
219/219 [==============================] - 2s 2ms/step - loss: 0.5886 - accuracy: 0.7160
Epoch 2/100
219/219 [==============================] - 0s 2ms/step - loss: 0.4874 - accuracy: 0.7980
Epoch 3/100
219/219 [==============================] - 0s 2ms/step - loss: 0.4525 - accuracy: 0.8001
Epoch 4/100
219/219 [==============================] - 0s 2ms/step - loss: 0.4339 - accuracy: 0.8030
Epoch 5/100
219/219 [==============================] - 0s 2ms/step - loss: 0.4203 - accuracy: 0.8050
Epoch 6/100
219/219 [==============================] - 1s 2ms/step - loss: 0.4063 - accuracy: 0.8156
Epoch 7/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3918 - accuracy: 0.8266
Epoch 8/100
219/219 [==============================] - 1s 2ms/step - loss: 0.3791 - accuracy: 0.8349
Epoch 9/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3700 - accuracy: 0.8417
Epoch 10/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3640 - accuracy: 0.8479
Epoch 11/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3606 - accuracy: 0.8503
Epoch 12/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3578 - accuracy: 0.8501
Epoch 13/100
219/219 [==============================] - 1s 2ms/step - loss: 0.3558 - accuracy: 0.8516
Epoch 14/100
219/219 [==============================] - 1s 2ms/step - loss: 0.3537 - accuracy: 0.8554
Epoch 15/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3518 - accuracy: 0.8557
Epoch 16/100
219/219 [==============================] - 1s 2ms/step - loss: 0.3507 - accuracy: 0.8569
Epoch 17/100
219/219 [==============================] - 1s 3ms/step - loss: 0.3492 - accuracy: 0.8573
Epoch 18/100
219/219 [==============================] - 1s 3ms/step - loss: 0.3482 - accuracy: 0.8584
Epoch 19/100
219/219 [==============================] - 1s 3ms/step - loss: 0.3470 - accuracy: 0.8577
Epoch 20/100
219/219 [==============================] - 1s 3ms/step - loss: 0.3462 - accuracy: 0.8604
Epoch 21/100
219/219 [==============================] - 1s 4ms/step - loss: 0.3458 - accuracy: 0.8586
Epoch 22/100
219/219 [==============================] - 1s 3ms/step - loss: 0.3445 - accuracy: 0.8590
Epoch 23/100
219/219 [==============================] - 1s 3ms/step - loss: 0.3444 - accuracy: 0.8607
Epoch 24/100
219/219 [==============================] - 1s 3ms/step - loss: 0.3435 - accuracy: 0.8590
Epoch 25/100
219/219 [==============================] - 1s 3ms/step - loss: 0.3428 - accuracy: 0.8591
Epoch 26/100
219/219 [==============================] - 1s 3ms/step - loss: 0.3420 - accuracy: 0.8601
Epoch 27/100
219/219 [==============================] - 1s 3ms/step - loss: 0.3419 - accuracy: 0.8616
Epoch 28/100
219/219 [==============================] - 1s 4ms/step - loss: 0.3413 - accuracy: 0.8601
Epoch 29/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3413 - accuracy: 0.8583
Epoch 30/100
219/219 [==============================] - 1s 2ms/step - loss: 0.3403 - accuracy: 0.8621
Epoch 31/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3405 - accuracy: 0.8613
Epoch 32/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3398 - accuracy: 0.8620
Epoch 33/100
219/219 [==============================] - 1s 2ms/step - loss: 0.3395 - accuracy: 0.8620
Epoch 34/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3395 - accuracy: 0.8609
Epoch 35/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3392 - accuracy: 0.8604
Epoch 36/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3393 - accuracy: 0.8624
Epoch 37/100
219/219 [==============================] - 1s 2ms/step - loss: 0.3391 - accuracy: 0.8603
Epoch 38/100
219/219 [==============================] - 1s 2ms/step - loss: 0.3389 - accuracy: 0.8614
Epoch 39/100
219/219 [==============================] - 1s 3ms/step - loss: 0.3383 - accuracy: 0.8617
Epoch 40/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3382 - accuracy: 0.8619
Epoch 41/100
219/219 [==============================] - 1s 2ms/step - loss: 0.3378 - accuracy: 0.8621
Epoch 42/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3377 - accuracy: 0.8619
Epoch 43/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3378 - accuracy: 0.8619
Epoch 44/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3374 - accuracy: 0.8630
Epoch 45/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3374 - accuracy: 0.8624
Epoch 46/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3371 - accuracy: 0.8643
Epoch 47/100
219/219 [==============================] - 1s 2ms/step - loss: 0.3368 - accuracy: 0.8614
Epoch 48/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3367 - accuracy: 0.8624
Epoch 49/100
219/219 [==============================] - 1s 3ms/step - loss: 0.3365 - accuracy: 0.8646
Epoch 50/100
219/219 [==============================] - 1s 3ms/step - loss: 0.3365 - accuracy: 0.8631
Epoch 51/100
219/219 [==============================] - 1s 3ms/step - loss: 0.3367 - accuracy: 0.8623
Epoch 52/100
219/219 [==============================] - 1s 3ms/step - loss: 0.3360 - accuracy: 0.8631
Epoch 53/100
219/219 [==============================] - 1s 3ms/step - loss: 0.3363 - accuracy: 0.8627
Epoch 54/100
219/219 [==============================] - 1s 3ms/step - loss: 0.3357 - accuracy: 0.8636
Epoch 55/100
219/219 [==============================] - 1s 3ms/step - loss: 0.3358 - accuracy: 0.8627
Epoch 56/100
219/219 [==============================] - 1s 3ms/step - loss: 0.3354 - accuracy: 0.8630
Epoch 57/100
219/219 [==============================] - 1s 3ms/step - loss: 0.3354 - accuracy: 0.8636
Epoch 58/100
219/219 [==============================] - 1s 3ms/step - loss: 0.3354 - accuracy: 0.8654
Epoch 59/100
219/219 [==============================] - 1s 3ms/step - loss: 0.3349 - accuracy: 0.8640
Epoch 60/100
219/219 [==============================] - 1s 3ms/step - loss: 0.3350 - accuracy: 0.8649
Epoch 61/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3348 - accuracy: 0.8641
Epoch 62/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3355 - accuracy: 0.8633
Epoch 63/100
219/219 [==============================] - 1s 2ms/step - loss: 0.3351 - accuracy: 0.8640
Epoch 64/100
219/219 [==============================] - 1s 2ms/step - loss: 0.3356 - accuracy: 0.8624
Epoch 65/100
219/219 [==============================] - 1s 2ms/step - loss: 0.3343 - accuracy: 0.8641
Epoch 66/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3348 - accuracy: 0.8641
Epoch 67/100
219/219 [==============================] - 1s 2ms/step - loss: 0.3346 - accuracy: 0.8650
Epoch 68/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3348 - accuracy: 0.8640
Epoch 69/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3345 - accuracy: 0.8640
Epoch 70/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3345 - accuracy: 0.8630
Epoch 71/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3346 - accuracy: 0.8643
Epoch 72/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3344 - accuracy: 0.8637
Epoch 73/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3343 - accuracy: 0.8661
Epoch 74/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3343 - accuracy: 0.8629
Epoch 75/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3340 - accuracy: 0.8657
Epoch 76/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3342 - accuracy: 0.8650
Epoch 77/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3340 - accuracy: 0.8650
Epoch 78/100
219/219 [==============================] - 1s 2ms/step - loss: 0.3346 - accuracy: 0.8647
Epoch 79/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3342 - accuracy: 0.8657
Epoch 80/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3339 - accuracy: 0.8650
Epoch 81/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3340 - accuracy: 0.8641
Epoch 82/100
219/219 [==============================] - 1s 4ms/step - loss: 0.3339 - accuracy: 0.8629
Epoch 83/100
219/219 [==============================] - 1s 3ms/step - loss: 0.3340 - accuracy: 0.8633
Epoch 84/100
219/219 [==============================] - 1s 3ms/step - loss: 0.3338 - accuracy: 0.8644
Epoch 85/100
219/219 [==============================] - 1s 3ms/step - loss: 0.3336 - accuracy: 0.8636
Epoch 86/100
219/219 [==============================] - 1s 3ms/step - loss: 0.3339 - accuracy: 0.8654
Epoch 87/100
219/219 [==============================] - 1s 3ms/step - loss: 0.3336 - accuracy: 0.8640
Epoch 88/100
219/219 [==============================] - 1s 4ms/step - loss: 0.3333 - accuracy: 0.8643
Epoch 89/100
219/219 [==============================] - 1s 3ms/step - loss: 0.3336 - accuracy: 0.8649
Epoch 90/100
219/219 [==============================] - 1s 3ms/step - loss: 0.3336 - accuracy: 0.8644
Epoch 91/100
219/219 [==============================] - 1s 4ms/step - loss: 0.3336 - accuracy: 0.8636
Epoch 92/100
219/219 [==============================] - 1s 3ms/step - loss: 0.3333 - accuracy: 0.8633
Epoch 93/100
219/219 [==============================] - 1s 3ms/step - loss: 0.3336 - accuracy: 0.8650
Epoch 94/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3335 - accuracy: 0.8646
Epoch 95/100
219/219 [==============================] - 1s 2ms/step - loss: 0.3335 - accuracy: 0.8630
Epoch 96/100
219/219 [==============================] - 1s 3ms/step - loss: 0.3330 - accuracy: 0.8654
Epoch 97/100
219/219 [==============================] - 1s 2ms/step - loss: 0.3338 - accuracy: 0.8644
Epoch 98/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3331 - accuracy: 0.8650
Epoch 99/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3336 - accuracy: 0.8643
Epoch 100/100
219/219 [==============================] - 0s 2ms/step - loss: 0.3331 - accuracy: 0.8636

### Let's make predictions and also experiments on the dataset

Geography: France

CreditScore: 600

Gender: Male

Age: 40 yrs

Tenure: 3 yrs

Balanace: $60000

number of products: 2

Has Credit card: Yes or No?

Customer Active: Yes or No?

Estimated Salary: $50000

Exited: yes or no?

In [ ]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [ ]:
# Lets make predictions and any predictions method must be 2D array
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)
# Fit transform used to get means values and comparing with threhold value 0.5

1/1 [==============================] - 0s 30ms/step
[[False]]

**Important note-1:**  Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects 2D arrays as the format of its input and putting our values into a double pair of square brackets makes the input excatly a 2D array.

**Important note-2:** "france" column was not a input as a string in the last column but as "1, 0, 0" in the first three columns. Thats because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of the features X, "france" was encoded as "1, 0, 0" and be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

## Predicting the Test set results

In [ ]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)),1))

94/94 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [1 1]]

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[2247  132]
 [ 299  322]]

0.8563333333333333